/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author Diegu7
 */
public class ButtonsP extends javax.swing.JPanel {

    /**
     * Creates new form ButtonsP
     */
    public JButton[][] grid;
    
    public ButtonsP() {
        initComponents();
        this.setLayout(new GridLayout(10,10));
        grid=new JButton[10][10]; //allocate the size of grid
        for(int y=0; y<10; y++){
            for(int x=0; x<10; x++){
                    grid[x][y]=new JButton((char)(65+x)+""+y); //creates new button
                    grid[x][y].addMouseListener(new java.awt.event.MouseAdapter() {
                            @Override
                            public void mouseReleased(java.awt.event.MouseEvent evt) {
                            }
                        });
                    this.add(grid[x][y]); //adds button to grid
            }
        }
    }
    
    public void buttonPressed(java.awt.event.MouseEvent evt, int x, int y){
        System.out.println(x + " - " + y);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMinimumSize(new java.awt.Dimension(700, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
