/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import javax.swing.table.DefaultTableModel;
import marveltry1.MainPro;
import objects.Usuario;
/**
 *
 * @author Diegu7
 */
public class GameP extends javax.swing.JPanel {

    /**
     * Creates new form GameP
     */
    public static Usuario player1;
    public static Usuario player2;
    
    public GameP(Usuario player1, Usuario player2) {
        initComponents();
        this.player1 = player1;
        this.player2 = player2;
        ButtonsP.player1 = player1;
        ButtonsP.player2 = player2;
        ButtonsP.currentPlayer = player1;
        ButtonsP.notCurrent = player2;
        lTurnoDe.setText(player1.getNombre());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonsP1 = new visual.ButtonsP();
        bRendir = new javax.swing.JButton();
        lTurnoDe = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tVillainDed = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tHeroDed = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));

        buttonsP1.setPreferredSize(new java.awt.Dimension(700, 700));

        bRendir.setText("RENDIRSE");
        bRendir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bRendirMouseReleased(evt);
            }
        });

        lTurnoDe.setText("Turno de: ");

        tVillainDed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Defeated Villains"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tVillainDed);
        if (tVillainDed.getColumnModel().getColumnCount() > 0) {
            tVillainDed.getColumnModel().getColumn(0).setResizable(false);
        }

        tHeroDed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fallen Heroes"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tHeroDed);
        if (tHeroDed.getColumnModel().getColumnCount() > 0) {
            tHeroDed.getColumnModel().getColumn(0).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(buttonsP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bRendir, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(lTurnoDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(lTurnoDe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bRendir)
                .addGap(313, 313, 313))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonsP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 6, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    public static void setLabel(String s){
        lTurnoDe.setText(s);
    }
    
    public void addDedVillain(String lol){
        DefaultTableModel model = (DefaultTableModel) tVillainDed.getModel();
        model.addRow(new Object[]{lol});
    }
    
    public void addDedHero(String lol){
        DefaultTableModel model = (DefaultTableModel) tHeroDed.getModel();
        model.addRow(new Object[]{lol});
    }
    
    private void bRendirMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bRendirMouseReleased
        MainPro.lol.setPanel(new MainMenuP(player1));
    }//GEN-LAST:event_bRendirMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bRendir;
    private visual.ButtonsP buttonsP1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private static javax.swing.JLabel lTurnoDe;
    private javax.swing.JTable tHeroDed;
    private javax.swing.JTable tVillainDed;
    // End of variables declaration//GEN-END:variables
}
