/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import marveltry1.MainPro;

/**
 *
 * @author Diegu7
 */
public class LoginP extends javax.swing.JPanel {

    /**
     * Creates new form LoginP
     */
    public LoginP() {
        initComponents();
    }
    
    public String takeUsuario(){
        return fUsuario.getText();
    }
    
    public String takePassword(){
        return fPassword.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fUsuario = new javax.swing.JTextField();
        fPassword = new javax.swing.JPasswordField();

        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));

        fUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fUsuario.setText("username");
        fUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fUsuarioMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                fUsuarioMouseReleased(evt);
            }
        });
        fUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fUsuarioActionPerformed(evt);
            }
        });

        fPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fPassword.setText("password");
        fPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                fPasswordMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(510, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(fUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(fPassword, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(510, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(261, 261, 261)
                .addComponent(fUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(fPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(352, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fPasswordMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fPasswordMouseReleased
        fPassword.setText("");
    }//GEN-LAST:event_fPasswordMouseReleased

    private void fUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fUsuarioActionPerformed

    private void fUsuarioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fUsuarioMouseReleased
        fUsuario.setText("");
    }//GEN-LAST:event_fUsuarioMouseReleased

    private void fUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fUsuarioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_fUsuarioMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField fPassword;
    private javax.swing.JTextField fUsuario;
    // End of variables declaration//GEN-END:variables
}
