
package visual;

import marveltry1.MainPro;
import objects.Usuario;

public class NewGameP extends javax.swing.JPanel {

    private Usuario player1;
    
    public NewGameP(Usuario player1) {
        initComponents();
        this.player1 = player1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bPartidaNueva = new javax.swing.JButton();
        bCargarPartida = new javax.swing.JButton();
        bEliminarPartida = new javax.swing.JButton();
        bRegresar = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(1280, 720));

        bPartidaNueva.setText("Partida Nueva");
        bPartidaNueva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bPartidaNuevaMouseReleased(evt);
            }
        });

        bCargarPartida.setText("Cargar Partida");
        bCargarPartida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bCargarPartidaMouseReleased(evt);
            }
        });

        bEliminarPartida.setText("Eliminar Partida");
        bEliminarPartida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bEliminarPartidaMouseReleased(evt);
            }
        });

        bRegresar.setText("Regresar");
        bRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bRegresarMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(540, 540, 540)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bPartidaNueva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bCargarPartida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bEliminarPartida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(bRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(540, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(bPartidaNueva)
                .addGap(60, 60, 60)
                .addComponent(bCargarPartida)
                .addGap(60, 60, 60)
                .addComponent(bEliminarPartida)
                .addGap(60, 60, 60)
                .addComponent(bRegresar)
                .addContainerGap(226, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bRegresarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bRegresarMouseReleased
        MainPro.lol.setPanel(new MainMenuP(player1));
    }//GEN-LAST:event_bRegresarMouseReleased

    private void bPartidaNuevaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPartidaNuevaMouseReleased
        MainPro.lol.setPanel(new PlayerComboP(player1));
    }//GEN-LAST:event_bPartidaNuevaMouseReleased

    private void bCargarPartidaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCargarPartidaMouseReleased
        MainPro.lol.showMessage("Aviso","PROXIMAMENTE", 1);
    }//GEN-LAST:event_bCargarPartidaMouseReleased

    private void bEliminarPartidaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bEliminarPartidaMouseReleased
        MainPro.lol.showMessage("Aviso","PROXIMAMENTE", 1);
    }//GEN-LAST:event_bEliminarPartidaMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCargarPartida;
    private javax.swing.JButton bEliminarPartida;
    private javax.swing.JButton bPartidaNueva;
    private javax.swing.JButton bRegresar;
    // End of variables declaration//GEN-END:variables
}
